# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    secret: '%env(APP_SECRET)%'
    csrf_protection: true
    http_method_override: false
    handle_all_throwables: true

    # Enables session support. Note that the session will ONLY be started if you read or write from it.
    # Remove or comment this section to explicitly disable session support.
    session:
        handler_id: null
        cookie_secure: auto
        cookie_samesite: lax
        storage_factory_id: session.storage.factory.native

    php_errors:
        log: true

    # Configure the cache
    cache:
        # Unique name of your app: used to compute stable namespaces for cache keys.
        #prefix_seed: your_vendor_name/app_name

        # The "app" cache stores to the filesystem by default.
        # The data in this cache should persist between deploys.
        # Other options: cache.adapter.redis, cache.adapter.memcached, cache.adapter.pdo, cache.adapter.in_memory, cache.adapter.array
        app: cache.adapter.filesystem

        # The "system" cache is for Symfony's internal use.
        # The data in this cache should NOT persist between deploys.
        system: cache.adapter.system

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file 